### ISSUE TITLE
Prefilter callback on property name

### ISSUE THREAD

**Issue by station384** [lightswitch05/table-to-json#16]
One issue I have come across is when a table header has an odd name
example 
 'Col 1 / ID'

this is valid it would render as
{'Col 1 / ID': 'someValue'}

but parsing it is where it becomes an issue.   It can be used in JavaScript by calling it as
var col1 = parsedJson['Col 1 / ID'];
but you can't call it as 
var col1 parsedJson.Col 1 / ID;

This issue is even more pronounced in other languages, C#, Java, Tcl.

The person could filter the JSON text and clean the property names, but that would be a lot of logic that would have to be implemented, or done in a regex that is beyond me.

What I propose is adding a new option. if the option is null or undefined,  the current behavior continues.  But if there is a function object, we call that function and pass in the string that is going to be set as the property, the return value from the function is what we use as the property.

something like this.

```
tableToJSON(
{ 
   callbackFunction : function (data) { return data.replace('/','').replace(' ','_' ); }
});
```

This gives the option to the end user to filter text,  process it,  map it if they want.   

I can implement it. 
##

**Comment by Mottie** [comment]
Actually, now that I've read this issue again, it's not about using the `textExtractor`. I thought that the `headings` option is used to replace header text and name the "key" in the key:value pairs of the JSON.
