### ISSUE TITLE
Unable to get values of the editable cells

### ISSUE THREAD

**Issue by Nagesh29** [lightswitch05/table-to-json#20]
This is great plugin to convert html table to json objects. It worked perfectly fine for me until now.
But I have two table cells which are editable for the user, so I have put input tag inside my td.
I am getting the values of all the table cells except two td's having input element present inside it.

Can you please help me out with this issue?

Thanks

**Comment by lightswitch05** [comment]
@Nagesh29 at the moment there is no way to get values from inputs. There are two tickets open (#14 & #16) for adding the functionality to handle inputs, but they are still in progress.

However, if you are want to keep using table-to-json, you could make use of the `data-override` option. After the input has been changed, just save the value into `data-override` to allow table-to-json to use it.
