### ISSUE TITLE
Values from COLSPAN duplicated

### ISSUE THREAD

**Issue by bdolnik** [lightswitch05/table-to-json#23]
Hi, thanks for this code... finding it very useful. One thing we are running into is when using a table with colspan, the value is duplicated in the json output.

So for instance I have a table with 2 rows and 3 columns, and a COLSPAN. The values in the table would be row1: c1, c2, c3 | row2: c4, c5 (COLSPAN on columns 1 and 2 of second row).

The JSON output looks like this...

c1,c2,c3
c4,c4,c5

Any way around this?
##

**Comment by lightswitch05** [comment]
You should have a look at the `rewrite` branch. It is a complete re-write and had better colspan and rowspan handling. The only reason it hasn't been released yet is because I was hoping to add more features in terms of events and hooks - but at this rate I should probably go ahead and release it.

**Comment by lightswitch05** [comment]
Actually - I think I misunderstood your request. After re-reading your question, it looks like the code is working how it is supposed to - but that you want to turn off `colspan` support.

| H1  | H2 | H3
| ---- | ----- | ---- |
| R1C1       | R1C2   | R1C3   |
| R2C1       | R2C1 (spanned)   | R2C3   |

How it currently works
-----------------------------

```JSON
[
    {
        "H1": "R1C1",
        "H2": "R1C2",
        "H3": "R1C3"
    }, {
        "H1": "R2C1",
        "H2": "R2C1",
        "H3": "R2C3"
    }
]
```

How you would like it to work?
-----------------------------

```JSON
[
    {
        "H1": "R1C1",
        "H2": "R1C2",
        "H3": "R1C3"
    }, {
        "H1": "R2C1",
        "H2": null,
        "H3": "R2C3"
    }
]
```

Am I understanding this correctly?

**Comment by bdolnik** [comment]
Yes that's correct, a null value in there would seem to make more sense.

**Comment by rattozone** [comment]
Is there any solution with olspan and rowspan support?

**Comment by lightswitch05** [comment]
@rattozone yes, colspan and rowspan are supported

**Comment by lightswitch05** [comment]
closing do to inactivity
