### ISSUE TITLE
Bug in Demo

### ISSUE THREAD

**Issue by georgeu2000** [lightswitch05/table-to-json#33]
Apparently there is a bug on http://www.developerdan.com/table-to-json/.

When I click convert,

![image](https://cloud.githubusercontent.com/assets/794632/18803667/f29a3a96-81a6-11e6-9cde-3f51f7953b1d.png)

This seems strange because the first row's points are 50, but the JSON is "disqualified".

Also, the 3rd header is Points, but JSON is "Score".

**Comment by lightswitch05** [comment]
Look at the HTML. This example is showing options to modify results, it is not a bug.

**Comment by georgeu2000** [comment]
In that case, you may want to explain that on the page. It seems to suggest that options are not being used:

```
  var table = $('#example-table').tableToJSON(); // Convert the table into a javascript object
  console.log(table);
  alert(JSON.stringify(table));
```

**Comment by lightswitch05** [comment]
Yes, I completely agree. Pull requests welcome!

**Comment by georgeu2000** [comment]
I wanted to update the docs, but I don't see how to do so. The issue is not on the readme in the repo. The issue is on http://www.developerdan.com/table-to-json/.

**Comment by Mottie** [comment]
Try the [gh-pages](https://github.com/lightswitch05/table-to-json/tree/gh-pages) branch.

**Comment by georgeu2000** [comment]
@Mottie - Thanks.
