### ISSUE TITLE
Can we have a little more explanation?

### ISSUE THREAD

**Issue by DanJ210** [lightswitch05/table-to-json#36]
I've been using this plugin so far and I'm a software engineer at a company. I would like to use this and I can as is but I'm trying to enable the feature to allowHTML. All I see as an explanation is that these are options but if I've never used plugins before and this is me learning... How do I know what that means?

You guys/girls have some great examples. I only wish and perhaps I recommend that there be one showing the options in use so that someone like me can easily learn and see. Maybe someone can give me a hint here so I can continue testing this plugin out and seeing how I'm going to use it?

Thanks for the plugin and I appreciate the work you all have done.

**Comment by lightswitch05** [comment]
Hello @DanJ210,

This project is mostly in a maintenance mode. I'm happy to review and merge pull requests, but I will not be making any major new changes myself, including documentation.

The options have a line of description on the home page: http://www.developerdan.com/table-to-json/

The option `allowHTML` is described as: `Boolean if HTML tags in table cells should be preserved.`

As an example, If I have a  cell: `<td><bold>Eve</bold></td>`, by default table-to-json will read that cell as `Eve`. But if you set `allowHTML` to `true`, then it will read the cell as `<bold>Eve</bold>`. This could be useful if you have data embedded in the cell as HTML.

I hope that answers your questions. You can easily play around with table-to-json by using this Plunker template: http://plnkr.co/edit/iQFtcEEZkvsMJ2UqcrlW?p=preview

**Comment by DanJ210** [comment]
I will play around with it some more and see if I can get them figured out now that I'm a little more knowledgeable on how these things work. But even some small documentation additions wouldn't hurt which show some of the "turning on options" that are available to use. Maybe seasoned people don't need this so it may not be worth your time even though a couple additional lines could go a long way.

Thanks a lot for the plugin and the work. Cool stuff for sure!
