### ISSUE TITLE
Wrong version number in release 0.12.0

### ISSUE THREAD

**Issue by SiamKreative** [lightswitch05/table-to-json#40]
In the minified file it shows `/*! table-to-json - v0.11.1 - Daniel White */`

**Comment by lightswitch05** [comment]
Thanks for pointing this out. The good news is that I have a pull request ready for another release, the bad new's (for others) is that I have a 5 day old and no time to do anything that requires more then my phone

**Comment by lightswitch05** [comment]
fixed in 0.13.0
