### ISSUE TITLE
To add <td id="value" in json data

### ISSUE THREAD

**Issue by Brhmts** [lightswitch05/table-to-json#41]
Hi 

Firstly , Thanks for this amazing plugin, It saved lots of time

This is not an issue.  Just I need some advice. How Could I get the td values ( <td id ="value") from each row and add it in JSON data ?

**Comment by lightswitch05** [comment]
@Brhmts use `extractor` feature.

```
$('table').tableToJSON({
  extractor : function(cellIndex, $cell) {
    // get text from the span inside table cells;
    // if empty or non-existant, get the cell text
    return $cell.attr('id') || $cell.text();
  }
});
```
