### ISSUE TITLE
Facing problem on the table with multiple tr in thead 

### ISSUE THREAD

**Issue by abdulwahabplus** [lightswitch05/table-to-json#43]
This my table structure : http://plnkr.co/edit/cD3E1wcQe6HjCwMsUgxs?p=preview

I am expecting the JSON as : `[{"Name":"Oscar","Age":"23","Grade":"16.5","Address":"1st street, orange city", SSN : 235345345}]`

Is it possible or is there any work around... 

Thanks

**Comment by Mottie** [comment]
Add a `headings` option:

```js
$('#run').click( function() {
     var table = $('#students').tableToJSON({
       headings: ['Name', 'Age', 'Grade', 'Address', 'SSN']
     });
     alert(JSON.stringify(table));  
});
```

I'm not sure why the `thead` content is included in the results... it's been a while since I looked at the code.

**Comment by abdulwahabplus** [comment]
Thanks a lot for the quick response :)

I will handle it by removing first 2 rows from the result.
