### ISSUE TITLE
Ability to include hidden columns

### ISSUE THREAD

**Issue by SRaiz** [lightswitch05/table-to-json#47]
Hi,

Is it possible to include the hidden columns also.

**Comment by lightswitch05** [comment]
@SRaiz hidden columns should already be included. See [this example](http://plnkr.co/edit/wSbLRop9OrVRhny7T4BI?p=preview) where the `Name` column is hidden, but still shows in the resulting JSON. Perhaps provide an example to demonstrate your issue

**Comment by SRaiz** [comment]
@lightswitch05 ...I was using **tablesorter** plugin to create my table. So it has an attribute "Visible" which can be set to yes or no for different columns. Then when you make the visibility as no for columns, the plugin is not able to take the data from that column. Although I have solved my issue by appending the required values in the visible fields and getting those values through JS in my function. Hence question is not invalid I believe. However thanks for the plugin...:)
