### ISSUE TITLE
how to install package and which files do I need?

### ISSUE THREAD

**Issue by mouaadBenAllal** [lightswitch05/table-to-json#48]
Hello,

I want to use this package with c# asp.net and jQuery. How do I get this package working? Is it something like the cdn link and which files do I need to get it working?

Thank you in advance.

Greetings,
Mouaad

**Comment by lightswitch05** [comment]
@mouaadBenAllal please use this CDN: https://cdn.jsdelivr.net/npm/table-to-json@0.12.0/lib/jquery.tabletojson.min.js

```
<script src="https://cdn.jsdelivr.net/npm/table-to-json@0.12.0/lib/jquery.tabletojson.min.js" integrity="sha256-DHUfNT1IN/qr+ceqzwa0zRo1avnACEPW5qFtqMXocuw=" crossorigin="anonymous"></script>
```

**Comment by lightswitch05** [comment]
Actually, that is an old version. Here is an updated one:

```
<script src="https://cdn.jsdelivr.net/npm/table-to-json@0.13.0/lib/jquery.tabletojson.min.js" integrity="sha256-AqDz23QC5g2yyhRaZcEGhMMZwQnp8fC6sCZpf+e7pnw=" crossorigin="anonymous"></script>
```

I added a section to the README for this
