### ISSUE TITLE
Can we get JSON for only selected rows of table?

### ISSUE THREAD

**Issue by raajig** [lightswitch05/table-to-json#49]

**Comment by lightswitch05** [comment]
No @raajig, it will always give you all rows back. There is no concept of row selection in HTML anyways.

**Comment by raajig** [comment]
I am using Jquery data tables and there we have option to select multiple
rows. So i am looking for selected rows conversion to JSON string.

Thanks for your reply.

Raji

**Comment by lightswitch05** [comment]
I recommend converting the whole table and then removing the rows you do not want. I will not be adding this feature since it is specific to data tables tool and not regular HTML tables.
