### ISSUE TITLE
Hi there :-) great library .. is there any chance it to have a reverse option ?

### ISSUE THREAD

**Issue by denden4444** [lightswitch05/table-to-json#50]
hi 

Thanks a for a great library.

My issue is actually a question.
Have you got a simple way (either in code which would be cool ) of taking the JSON data back to a table again ?
It would be great to have the option to pop table data out and then back in again :-)

I look forward to your reply 

Den

**Comment by lightswitch05** [comment]
I'm glad you enjoy this library. There is no way for this tool to create a table. You might be interested in [DataTables](https://www.datatables.net/) for generating tables
