### ISSUE TITLE
Can table conversion with input be supported?

### ISSUE THREAD

**Issue by supermanzzZ** [lightswitch05/table-to-json#51]
There are some inputs in my table, and I want to convert the values in input to json.Now the effect is to skip the input value directly.Is there any solution? Thanks

**Comment by Mottie** [comment]
Hi @supermanzzZ!

Use the [`extractor` option](https://github.com/lightswitch05/table-to-json#options) to get the input value instead of the text.

**Comment by supermanzzZ** [comment]
Thank you a lot for your reply :)
I'm sorry I didn't read the document in detail.
