### ISSUE TITLE
empty data array when calling tableToJSON() on my table

### ISSUE THREAD

**Issue by Slos** [lightswitch05/table-to-json#56]
I have a pretty standard table on my HTML page (see screenshot). Yet, when I try to extract the cell data I get back a empty data array.

`var data = $('#testTable').tableToJSON()
    console.log(data)`

==> []

<img width="556" alt="image" src="https://user-images.githubusercontent.com/9729859/108824564-27fe1400-75c2-11eb-99f8-0136e3a8bc09.png">

**Comment by Mottie** [comment]
It appears that the rows are not inside a `<tbody>`.
