### ISSUE TITLE
Without jQuery and types

### ISSUE THREAD

**Issue by cristiammercado** [lightswitch05/table-to-json#57]
Hi,

First of all many thanks for the excellent work of the plugin.

I know this project is a jQuery plugin, but:

- Is it possible to make a version that doesn't have jQuery as a dependency? 
- Other suggestion is if you could publish this project with types? I'm migrating a project from AngularJS to Angular and hopefully it was possible for the project to export the types to be used in this type of project with Typescript. 

Thanks!

**Comment by lightswitch05** [comment]
> Is it possible to make a version that doesn't have jQuery as a dependency?

It is possible, but it would be a completely new project then this

> Other suggestion is if you could publish this project with types?

This project is really just in maintenance mode at this point. If you want to submit a PR to do this, I would consider it, but I'm not sure this is really the correct tool for the job in most cases, and so I'm hesitant to add more stuff to it.
